### ISSUE TITLE
fix path private_key_path and public_key_path

### ISSUE THREAD

**Issue by oussaka** [jpsymfony/REST-BEHAT#2]
Dans le parameters.yml.dist, il y a une erreur dans le path private_key_path et public_key_path. Ils doivent être :
 
```
    private_key_path:   %kernel.root_dir%/../var/jwt/private.pem
    public_key_path:    %kernel.root_dir%/../var/jwt/public.pem
```

**Comment by jpsymfony** [comment]
Non car dans Symfony2, %kernel.root_dir% pointe vers app, et j'ai créé un répertoire var dans app. Si on fait %kernel.root_dir%/../var/jwt/private.pem, alors je devrais mettre le répertoire jwt dans un répertoire var à la racine du projet (ce qui est ok pour Symfony3)
